services:
  qgis:
    image: qgis-server
    build:
      context: .
    restart: unless-stopped
    ports:
      - 8000:8000
      - 8001:8001
    volumes:
      - .:/data
    working_dir: /data
    command: "make -j qgis mapproxy"
