version: "3.4"

services:
  qgis:
    image: qgis-server
    build:
      context: .
    restart: unless-stopped
    ports:
      - 8000:8000
      - 8001:8001
    volumes:
      - .:/data
    working_dir: /data
    environment:
      QGIS_SERVER_PARALLEL_RENDERING: "1"
      QGIS_SERVER_LANDING_PAGE_PROJECTS_DIRECTORIES: "/data/tiles"
    command: "sh -c 'qgis_mapserver -p bsh.qgs & mapproxy-util serve-develop mapproxy.yaml -b 0.0.0.0:8001'"
