site_name: Free Nautical Charts
site_url: http://waddenzee.duckdns.org/download/
repo_url: https://github.com/quantenschaum/mapping
repo_name: quantenschaum/mapping
edit_uri: -/docs/

# pip install mkdocs mkdocs-material mkdocs-git-revision-date-localized-plugin

nav:
  - Chart: http://waddenzee.duckdns.org/
  - Download: index.md

theme:
  name: material
  language: en
  logo: compass.svg
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-sunny
        name: bright
      primary: blue
      accent: orange
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-night
        name: dark
      primary: indigo
      accent: deep orange
  font:
    text: Ubuntu
    code: Fira Code
  features:
    - navigation.top
    #    - navigation.instant
    - navigation.tracking
    #    - navigation.tabs
    #    - navigation.tabs.sticky
    #    - navigation.sections
    - navigation.expand
    - toc.follow

markdown_extensions:
  - admonition
  #  - pymdownx.details
  #  - pymdownx.highlight:
  #      anchor_linenums: true
  #  #  - pymdownx.inlinehilite
  #  #  - pymdownx.snippets
  #  - pymdownx.superfences:
  #      custom_fences:
  #        - name: mermaid
  #          class: mermaid
  #          format: !!python/name:pymdownx.superfences.fence_code_format
  #  - def_list
  - attr_list
#  - tables
#  - smarty
#  - pymdownx.smartsymbols
#  - pymdownx.critic
#  - pymdownx.caret
#  - pymdownx.keys
#  - pymdownx.mark
#  - pymdownx.tilde
#  - pymdownx.magiclink
#  - footnotes
#  - pymdownx.emoji:
#      emoji_index: !!python/name:materialx.emoji.twemoji
#      emoji_generator: !!python/name:materialx.emoji.to_svg
#  - pymdownx.tasklist:
#      custom_checkbox: true
#  - toc:
#      permalink: true
#  - pymdownx.arithmatex:
#      generic: true

#extra:
#  #  homepage: https://example.com
#  version:
#    provider: mike

#extra_javascript:
#  - js/katex.js
#  - https://cdn.jsdelivr.net/npm/katex@0.16.1/dist/katex.min.js

#extra_css:
#  - https://cdn.jsdelivr.net/npm/katex@0.16.10/dist/katex.min.css

plugins:
  - search:
      lang: en
  - git-revision-date-localized:
      #      enable_creation_date: true
      type: iso_date


